[2024-04-15T17:10:30.408+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dbt_visualization.generate_visualizations manual__2024-04-15T17:06:57.902157+00:00 [queued]>
[2024-04-15T17:10:30.413+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dbt_visualization.generate_visualizations manual__2024-04-15T17:06:57.902157+00:00 [queued]>
[2024-04-15T17:10:30.414+0000] {taskinstance.py:2171} INFO - Starting attempt 2 of 3
[2024-04-15T17:10:30.430+0000] {taskinstance.py:2192} INFO - Executing <Task(PythonOperator): generate_visualizations> on 2024-04-15 17:06:57.902157+00:00
[2024-04-15T17:10:30.435+0000] {standard_task_runner.py:60} INFO - Started process 6596 to run task
[2024-04-15T17:10:30.438+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'dbt_visualization', 'generate_visualizations', 'manual__2024-04-15T17:06:57.902157+00:00', '--job-id', '120', '--raw', '--subdir', 'DAGS_FOLDER/dbt_visualization.py', '--cfg-path', '/tmp/tmp4_6fizi1']
[2024-04-15T17:10:30.440+0000] {standard_task_runner.py:88} INFO - Job 120: Subtask generate_visualizations
[2024-04-15T17:10:30.478+0000] {task_command.py:423} INFO - Running <TaskInstance: dbt_visualization.generate_visualizations manual__2024-04-15T17:06:57.902157+00:00 [running]> on host ec3d883e7b78
[2024-04-15T17:10:30.556+0000] {taskinstance.py:2481} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='66130047@dpu.ac.th' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dbt_visualization' AIRFLOW_CTX_TASK_ID='generate_visualizations' AIRFLOW_CTX_EXECUTION_DATE='2024-04-15T17:06:57.902157+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-04-15T17:06:57.902157+00:00'
[2024-04-15T17:10:30.565+0000] {base.py:83} INFO - Using connection ID 'my_***_conn' for task execution.
[2024-04-15T17:10:30.580+0000] {logging_mixin.py:188} WARNING - /opt/***/dags/dbt_visualization.py:28 UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
[2024-04-15T17:10:30.698+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.8/site-packages/***/utils/context.py:315 AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
[2024-04-15T17:10:31.025+0000] {python.py:201} INFO - Done. Returned value was: None
[2024-04-15T17:10:31.034+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=dbt_visualization, task_id=generate_visualizations, execution_date=20240415T170657, start_date=20240415T171030, end_date=20240415T171031
[2024-04-15T17:10:31.093+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-04-15T17:10:31.112+0000] {taskinstance.py:3281} INFO - 0 downstream tasks scheduled from follow-on schedule check
